name: Macos

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'tools/**'
      - '.github/workflows/macos.yml'
      - 'external/**'
      - 'Makefile'

permissions:
  contents: read
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ macos-11, macos-12, macos-13, macos-14 ]
        gui: [ raylib, imgui, headless ]
    steps:
    - uses: actions/checkout@v3.6.0
    - uses: goto-bus-stop/setup-zig@v2.2.0
      with:
        version: 0.12.0
        cache: true
    - run: |
        ls
        zig build -Doptimize=ReleaseSafe -DGui=${{matrix.gui}} --summary all
        ls zig-out/bin

