name: Macos

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'tools/**'
      - '.github/workflows/macos.yml'
      - 'external/**'
      - 'Makefile'

permissions:
  contents: read
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.6.0
      with:
        submodules: true

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2.2.0
      with:
        version: 0.12.0
        cache: true

    - name: Build
      run: |
        ls
        zig build -Doptimize=ReleaseSafe --summary all
        ls zig-out/bin

