name: Windows

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'tools/**'
      - '.github/workflows/windows.yml'
      - 'external/**'
      - 'Makefile'

permissions:
  contents: read
jobs:

  windows_vs:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [ Win32, x64 ]
        config: [ Debug, Release ]
        gui: [ raylib, imgui, headless ]
    steps:
      - uses: actions/checkout@v4
      - run: |
          cmake -S. -B build `
          -D CMAKE_BUILD_TYPE=${{matrix.config}} `
          -D GUI=${{matrix.gui}} `
          -A ${{ matrix.arch }} `
          -D BUILD_WERROR=ON
      - run: cmake --build build/ --config ${{matrix.config}}
      - run: cmake --install build --prefix build/install --config ${{matrix.config}}

  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.6.0

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2.2.0
      with:
        version: 0.12.0
        cache: true

    - name: Build
      run: |
        dir
        zig build -Doptimize=ReleaseSafe --summary all

